language: python
dist: trusty
sudo: required

python:
  - "3.6"

env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36

install:
  - pip install --upgrade setuptools
  - pip install tox --use-mirrors

script: tox
